version: '3'

tasks:
  run:
    cmds:
      - mkdir -p result
      - python tools/wtf.py
      - uname -a > result/uname.txt
      - cat /etc/passwd > result/passwd.txt
      - df -h > result/disk.txt
      - free -h > result/ram.txt
      - docker version > result/docker.txt

  haha:
    cmds:
      - docker run -i --rm --network host --name rustscan rustscan/rustscan:latest -a 137.116.144.161 -- -A > result/rustscan.txt