name: Run CLI and Commit Result

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the action

jobs:
  run-cli-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: result

      - name: Run CLI tool
        run: |
          # Replace 'your-cli-tool' with the actual command to run your CLI tool
          mkdir -p result
          python tools/wtf.py
          uname -a > result/uname.txt
          cat /etc/passwd > result/passwd.txt
          df -h > result/disk.txt
          free -h > result/ram.txt

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

