name: Run CLI and Commit Result

on:
  push:
    branches:
      - main

jobs:
  run-cli-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CLI tool
        run: task run

      - name: Run rustscan docker
        run: task haha

      - name: Configure git
        run: |
          git config --global user.name 'Minaris'
          git config --global user.email 'minaris@kaitoz11.me'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Changes

